### ISSUE TITLE
Create method to look through yamls

### ISSUE THREAD

**Issue by kameghamegha** [kameghamegha/macos_configuration#4]
It should have three parameters: feature key name (something like `updates__auto_check`), macos version (something like `10.11`), and the action (only care about enable and disable for now). It will then look through the yaml and return all of the following values that are associated with that feature, action, and macos version:

```
    domain
    key
    action_value:
    sudo:
    global:
```

**Comment by dissonanz** [comment]
Could we avoid having to pass the platform version by using the [File Specificity](https://docs.chef.io/resource_template.html#file-specificity) directory structure and separating config yamls by platform version?

**Comment by kameghamegha** [comment]
I'd really hate to have separate lists where most of the list is honestly the same. We discussed this last night and decided that separate config yamls for versions was a bad idea and hard to maintain.
